# Generated by Django 5.1.3 on 2024-11-13 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
